fruits=['apple','banana','cherry']
print(fruits[1])
fruits[0]="kiwi"
print(fruits)
fruits.append('orange')
print(fruits)
fruits.insert(1,"lemon")
print(fruits)
fruits.remove("banana")
print(fruits)
print(fruits[-1])
print(fruits[2:4])
print(len(fruits))